import type React from "react";
import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next";
import { ModalProvider } from "@/components/modal-provider";
import { JsonLd } from "@/components/json-ld";
import "./globals.css";

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL ?? "https://www.butterflydec.com";

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),
  title: "Butterfly decor (Sostene Group)",
  description:
    "Butterfly decor is Where beauty meets celebration throught decoration and outfit rental, ,free wedding planning and other services for your special events.",
 keywords: [
  // =========================================================
  // BRAND
  // =========================================================
  "Butterfly Decor",
  "Butterfly decor",
  "Butterfly Decor Rwanda",
  "Butterfly Decor Kigali",
  "Butterfly Decoration",
  "Butterfly Decoration Rwanda",
  "Butterfly Decoration Kigali",
  "Butterfly Decor by Sostene",
  "Butterflydec",
  "butterflydec.com",
  "Sostene Group",
  "Sostene",
  "Sostene Decor",
  "Sostene Decoration",
  "Sostene Butterfly Decor",
  "Sostene Decor Rwanda",
  "Sostene Decor Kigali",
  "Sostene Decoration Rwanda",
  "Sostene Decoration Kigali",

  // =========================================================
  // GENERAL DECORATION & EVENTS
  // =========================================================
  "event decoration Rwanda",
  "event decoration Kigali",
  "event decor Rwanda",
  "event decor Kigali",
  "event decoration services Rwanda",
  "event decoration services Kigali",
  "event styling Rwanda",
  "event styling Kigali",
  "event design Rwanda",
  "event design Kigali",
  "event planner Rwanda",
  "event planner Kigali",
  "event planning Rwanda",
  "event planning Kigali",
  "event management Rwanda",
  "event management Kigali",
  "celebration decoration Rwanda",
  "celebration decoration Kigali",
  "party decoration Rwanda",
  "party decoration Kigali",
  "party planner Rwanda",
  "party planner Kigali",
  "decoration company Rwanda",
  "decoration company Kigali",
  "decor company Rwanda",
  "decor company Kigali",
  "decoration services Rwanda",
  "decoration services Kigali",
  "decor services Rwanda",
  "decor services Kigali",
  "decor studio Rwanda",
  "decor studio Kigali",
  "decoration studio Rwanda",
  "decoration studio Kigali",
  "professional decoration Rwanda",
  "professional decoration Kigali",
  "beautiful event decoration Rwanda",
  "luxury event decoration Rwanda",
  "elegant event decoration Rwanda",

  // =========================================================
  // WEDDING
  // =========================================================
  "wedding decoration Rwanda",
  "wedding decoration Kigali",
  "wedding decor Rwanda",
  "wedding decor Kigali",
  "wedding styling Rwanda",
  "wedding styling Kigali",
  "wedding design Rwanda",
  "wedding design Kigali",
  "wedding planner Rwanda",
  "wedding planner Kigali",
  "wedding planning Rwanda",
  "wedding planning Kigali",
  "wedding planning services Rwanda",
  "wedding planning services Kigali",
  "wedding decoration services Rwanda",
  "wedding decoration services Kigali",
  "wedding venue decoration Rwanda",
  "wedding venue decoration Kigali",
  "wedding reception decoration Rwanda",
  "wedding reception decoration Kigali",
  "wedding ceremony decoration Rwanda",
  "wedding ceremony decoration Kigali",
  "wedding setup Rwanda",
  "wedding setup Kigali",
  "wedding styling services Rwanda",
  "wedding styling services Kigali",
  "beautiful wedding decoration Rwanda",
  "elegant wedding decoration Rwanda",
  "modern wedding decoration Rwanda",
  "traditional wedding decoration Rwanda",
  "affordable wedding decoration Rwanda",
  "wedding decor ideas Rwanda",
  "wedding decoration ideas Kigali",

  // =========================================================
  // LOVE / ROMANCE / PROPOSAL / ENGAGEMENT
  // =========================================================
  "love decoration Rwanda",
  "love decoration Kigali",
  "romantic decoration Rwanda",
  "romantic decoration Kigali",
  "romantic event decoration Rwanda",
  "romantic event decoration Kigali",
  "romantic wedding decoration Rwanda",
  "romantic wedding decoration Kigali",
  "love celebration Rwanda",
  "love celebration Kigali",
  "couples decoration Rwanda",
  "couples decoration Kigali",
  "romantic setup Rwanda",
  "romantic setup Kigali",
  "romantic surprise Rwanda",
  "romantic surprise Kigali",
  "surprise decoration Rwanda",
  "surprise decoration Kigali",
  "surprise party decoration Rwanda",
  "surprise party decoration Kigali",
  "proposal decoration Rwanda",
  "proposal decoration Kigali",
  "marriage proposal decoration Rwanda",
  "marriage proposal decoration Kigali",
  "proposal setup Rwanda",
  "proposal setup Kigali",
  "engagement decoration Rwanda",
  "engagement decoration Kigali",
  "engagement party decoration Rwanda",
  "engagement party decoration Kigali",
  "anniversary decoration Rwanda",
  "anniversary decoration Kigali",
  "romantic dinner decoration Rwanda",
  "romantic dinner decoration Kigali",
  "date decoration Rwanda",
  "date decoration Kigali",

  // =========================================================
  // WEDDING ATTIRE / OUTFIT RENTAL
  // =========================================================
  "outfit rental Rwanda",
  "outfit rental Kigali",
  "wedding outfit rental Rwanda",
  "wedding outfit rental Kigali",
  "wedding dress rental Rwanda",
  "wedding dress rental Kigali",
  "bridal dress Rwanda",
  "bridal dress Kigali",
  "bridal gown Rwanda",
  "bridal gown Kigali",
  "bride dress Rwanda",
  "bride dress Kigali",
  "bride outfit Rwanda",
  "bride outfit Kigali",
  "groom outfit Rwanda",
  "groom outfit Kigali",
  "groom suit Rwanda",
  "groom suit Kigali",
  "wedding suits Rwanda",
  "wedding suits Kigali",
  "traditional wedding outfit Rwanda",
  "traditional wedding attire Rwanda",
  "traditional wedding attire Kigali",
  "mushanana Rwanda",
  "mushanana rental Rwanda",
  "mushanana rental Kigali",
  "wedding attire Rwanda",
  "wedding attire Kigali",
  "bridal wear Rwanda",
  "bridal wear Kigali",
  "bridesmaid dresses Rwanda",
  "bridesmaid dresses Kigali",
  "wedding outfit rental Kigali",

  // =========================================================
  // TRADITIONAL RWANDAN CEREMONIES
  // =========================================================
  "gusaba Rwanda",
  "gusaba decoration Rwanda",
  "gusaba decoration Kigali",
  "gusaba ceremony decoration",
  "gusaba ceremony Rwanda",
  "gusaba ceremony Kigali",
  "introduction ceremony Rwanda",
  "introduction ceremony decoration Rwanda",
  "introduction ceremony decoration Kigali",
  "traditional ceremony decoration Rwanda",
  "traditional ceremony decoration Kigali",
  "Rwandan traditional wedding decoration",
  "Rwandan traditional wedding decor",
  "Rwandan wedding decoration",
  "Rwandan wedding styling",
  "traditional wedding Rwanda",
  "traditional wedding Kigali",
  "Rwandan wedding attire",
  "Rwandan traditional attire",
  "Rwandan traditional decoration",

  // =========================================================
  // DECORATION ELEMENTS
  // =========================================================
  "flower decoration Rwanda",
  "flower decoration Kigali",
  "floral decoration Rwanda",
  "floral decoration Kigali",
  "floral arrangements Rwanda",
  "floral arrangements Kigali",
  "wedding flowers Rwanda",
  "wedding flowers Kigali",
  "wedding flower decoration",
  "event flowers Rwanda",
  "event flowers Kigali",
  "balloon decoration Rwanda",
  "balloon decoration Kigali",
  "balloon arch Rwanda",
  "balloon arch Kigali",
  "wedding backdrop Rwanda",
  "wedding backdrop Kigali",
  "event backdrop Rwanda",
  "event backdrop Kigali",
  "photo backdrop Rwanda",
  "photo backdrop Kigali",
  "wedding stage decoration Rwanda",
  "wedding stage decoration Kigali",
  "event stage decoration Rwanda",
  "event stage decoration Kigali",
  "wedding entrance decoration Rwanda",
  "wedding entrance decoration Kigali",
  "table decoration Rwanda",
  "table decoration Kigali",
  "table styling Rwanda",
  "table styling Kigali",
  "wedding table decoration Rwanda",
  "wedding table decoration Kigali",
  "chair decoration Rwanda",
  "chair decoration Kigali",
  "ceiling decoration Rwanda",
  "ceiling decoration Kigali",
  "draping Rwanda",
  "wedding draping Rwanda",
  "wedding draping Kigali",
  "event draping Rwanda",
  "event lighting Rwanda",
  "wedding lighting Rwanda",
  "wedding lights Kigali",
  "fairy lights Rwanda",
  "wedding centerpieces Rwanda",
  "wedding centerpieces Kigali",
  "event centerpieces Rwanda",
  "event centerpieces Kigali",

  // =========================================================
  // OTHER CELEBRATIONS
  // =========================================================
  "birthday decoration Rwanda",
  "birthday decoration Kigali",
  "birthday party decoration Rwanda",
  "birthday party decoration Kigali",
  "birthday planner Rwanda",
  "birthday planner Kigali",
  "baby shower decoration Rwanda",
  "baby shower decoration Kigali",
  "bridal shower decoration Rwanda",
  "bridal shower decoration Kigali",
  "graduation decoration Rwanda",
  "graduation decoration Kigali",
  "graduation party decoration Rwanda",
  "graduation party decoration Kigali",
  "anniversary decoration Rwanda",
  "anniversary decoration Kigali",
  "church event decoration Rwanda",
  "church event decoration Kigali",
  "church decoration Rwanda",
  "church decoration Kigali",
  "memorial decoration Rwanda",
  "memorial decoration Kigali",
  "corporate event decoration Rwanda",
  "corporate event decoration Kigali",
  "conference decoration Rwanda",
  "conference decoration Kigali",
  "private event decoration Rwanda",
  "private event decoration Kigali",
  "family celebration decoration Rwanda",
  "family celebration decoration Kigali",

  // =========================================================
  // OTHER SERVICES
  // =========================================================
  "free wedding planning Rwanda",
  "free wedding planning Kigali",
  "wedding consultation Rwanda",
  "wedding consultation Kigali",
  "wedding coordination Rwanda",
  "wedding coordination Kigali",
  "event coordination Rwanda",
  "event coordination Kigali",
  "gift wrapping Rwanda",
  "gift wrapping Kigali",
  "wedding invitations Rwanda",
  "wedding invitations Kigali",
  "event invitations Rwanda",
  "event invitations Kigali",
  "wedding stationery Rwanda",
  "wedding stationery Kigali",
  "wedding accessories Rwanda",
  "wedding accessories Kigali",
  "wedding tools Rwanda",
  "wedding supplies Rwanda",
  "event supplies Rwanda",
  "event accessories Rwanda",

  // =========================================================
  // KINYARWANDA — WEDDING & EVENTS
  // =========================================================
  "ubukwe Rwanda",
  "ubukwe Kigali",
  "gutaka ubukwe Rwanda",
  "gutaka ubukwe Kigali",
  "gutegura ubukwe Rwanda",
  "gutegura ubukwe Kigali",
  "gutegura ibirori Rwanda",
  "gutegura ibirori Kigali",
  "gutaka ibirori Rwanda",
  "gutaka ibirori Kigali",
  "imitako y'ubukwe",
  "imitako y'ubukwe Rwanda",
  "imitako y'ubukwe Kigali",
  "imitako y'ibirori",
  "imitako y'ibirori Rwanda",
  "imitako y'ibirori Kigali",
  "serivisi zo gutaka ibirori",
  "serivisi zo gutaka ubukwe",
  "gutaka inzu y'ibirori",
  "gutaka ahabera ubukwe",
  "gutaka aho ibirori bibera",
  "gutegura ibirori by'ubukwe",
  "gutegura ibirori Kigali",
  "umuhango w'ubukwe",
  "umuhango wo gusaba",
  "gusaba",
  "gusaba Rwanda",
  "gusaba Kigali",
  "gutaka gusaba",
  "gutaka gusaba Rwanda",
  "gutaka gusaba Kigali",

  // =========================================================
  // KINYARWANDA — LOVE / RELATIONSHIP
  // =========================================================
  "urukundo",
  "urukundo Rwanda",
  "urukundo Kigali",
  "gukunda",
  "abakundana",
  "ibirori by'abakundana",
  "imitako y'urukundo",
  "gutaka urukundo",
  "gutegura ibirori by'urukundo",
  "ibirori by'urukundo",
  "umunsi w'urukundo",
  "kwizihiza urukundo",
  "kwizihiza isabukuru y'abakundana",
  "isabukuru y'urukundo",
  "gutegura surprise",
  "surprise y'umukunzi",
  "gutegura surprise y'umukunzi",
  "gutaka surprise",
  "gutaka surprise Rwanda",
  "gutegura proposal",
  "proposal y'urukundo",
  "gusaba umukunzi",
  "gusaba urukundo",
  "gusaba uwo ukunda",
  "kwambika impeta",
  "ibirori byo kwambika impeta",
  "gutaka kwambika impeta",

  // =========================================================
  // KINYARWANDA — CLOTHING / OUTFITS
  // =========================================================
  "imyenda y'ubukwe",
  "imyenda y'umugeni",
  "umwenda w'umugeni",
  "umwenda w'umukwe",
  "imyenda y'umukwe",
  "imyenda y'abageni",
  "imyambaro y'ubukwe",
  "imyambaro y'umugeni",
  "imyambaro y'umukwe",
  "imyambaro y'ubukwe Rwanda",
  "gukodesha imyenda y'ubukwe",
  "gukodesha imyenda Kigali",
  "gukodesha umwenda w'umugeni",
  "gukodesha imyenda y'umugeni",
  "gukodesha imyenda y'umukwe",
  "imyenda y'ubukwe ikodeshwa",
  "mushanana",
  "mushanana Rwanda",
  "gukodesha mushanana",

  // =========================================================
  // KINYARWANDA — DECORATION ELEMENTS
  // =========================================================
  "indabyo z'ubukwe",
  "indabyo z'ibirori",
  "indabyo zo gutaka",
  "imitako y'indabyo",
  "balloon zo gutaka",
  "imipira yo gutaka",
  "amatara yo gutaka",
  "amatara y'ibirori",
  "umwenda wo gutaka",
  "imyenda yo gutaka",
  "ameza y'ubukwe",
  "gutaka ameza",
  "gutaka intebe",
  "gutaka stage",
  "stage y'ubukwe",
  "stage y'ibirori",
  "ahantu hafotorerwa ubukwe",
  "ahantu hafotorerwa ibirori",
  "gutaka ahantu hafotorerwa",

  // =========================================================
  // KINYARWANDA — OTHER EVENTS
  // =========================================================
  "gutaka isabukuru",
  "gutaka birthday",
  "gutaka ibirori by'isabukuru",
  "gutaka baby shower",
  "gutaka bridal shower",
  "gutaka graduation",
  "gutaka ibirori byo kwizihiza",
  "gutaka ibirori bya kiliziya",
  "gutaka ibirori bya church",
  "gutaka ibirori by'umuryango",
  "gutaka ibirori by'abageni",

  // =========================================================
  // GIFT / INVITATION
  // =========================================================
  "impano z'ubukwe",
  "gupfunyika impano",
  "gupfunyika impano Rwanda",
  "gupfunyika impano Kigali",
  "impapuro z'ubutumire",
  "ubutumire bw'ubukwe",
  "impapuro z'ubutumire bw'ubukwe",
  "ubutumire bw'ibirori",
  "gutegura ubutumire bw'ubukwe",

  // =========================================================
  // FRENCH
  // =========================================================
  "décoration mariage Rwanda",
  "décoration mariage Kigali",
  "décoration événement Rwanda",
  "décoration événement Kigali",
  "décoration fête Rwanda",
  "décoration fête Kigali",
  "organisation mariage Rwanda",
  "organisation mariage Kigali",
  "planification mariage Rwanda",
  "planification mariage Kigali",
  "décoration anniversaire Rwanda",
  "décoration anniversaire Kigali",
  "location tenue mariage Rwanda",
  "robe mariée Rwanda",
  "décoration florale Rwanda",
  "décoration florale Kigali",
  "décoration ballon Rwanda",
  "décoration salle mariage Rwanda",
  "décoration salle Kigali",
],
  authors: [{ name: "Butterfly Decor", url: BASE_URL }],
  creator: "Butterfly Decor",
  publisher: "Butterfly Decor",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "en_RW",
    alternateLocale: "rw_RW",
    url: BASE_URL,
    siteName: "Butterfly Decor Rwanda",
    title: "Butterfly Decor",
    description: "Event Decoration & Outfit Rental in Rwanda",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "Butterfly Decor Rwanda",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Butterfly Decor",
    description: "Event Decoration & Outfit Rental in Rwanda",
    images: ["/og-image.png"],
  },
  alternates: {
    canonical: BASE_URL,
    languages: {
      "en-RW": BASE_URL,
      rw: `${BASE_URL}/rw`,
    },
  },
  icons: {
    icon: "/icon.svg",
    apple: "/icon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en-RW">
      <head>
        <meta name="google-site-verification" content="PASTE_YOUR_CODE_HERE" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Playball&family=Plus+Jakarta+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
      </head>
      <body className="antialiased cursor-auto" style={{ fontFamily: "'Plus Jakarta Sans', sans-serif" }} suppressHydrationWarning>
        {children}
        <JsonLd />
        <ModalProvider />
        <Analytics />
      </body>
    </html>
  );
}
