export const butterflyItems = [
  { id: "a-1", name: "Background 01", image: "/decor01.jpg" },
  { id: "b-2", name: "Background 02", image: "/decor02.jpg" },
  { id: "d-3", name: "Background 03", image: "/decor03.jpg" },
  { id: "e-4", name: "Background 04", image: "/decor04.jpg" },
  { id: "f-5", name: "Elegant Decor", image: "/elegent_decor.png" },
  { id: "g-6", name: "Wedding Design", image: "/wedding.png" },
  { id: "h-7", name: "Bridal Collection", image: "/bridal.jpg" },
  { id: "i-8", name: "Venue Collection", image: "/venueCollection.jpg" },
  { id: "j-9", name: "Cake Collection", image: "/cakeCollection.jpg" },
  { id: "k-10", name: "Catering Collection", image: "/cateringCollection.jpg" },
  { id: "l-11", name: "Photography", image: "/photographerCollection.jpg" },
  { id: "m-12", name: "Florist Collection", image: "/flowerColection.jpg" },
  { id: "n-13", name: "Bridal Setup", image: "/bridalCollection.jpg" },
  { id: "o-14", name: "Background 01 B", image: "/decor01.jpg" },
  { id: "p-15", name: "Background 02 B", image: "/decor02.jpg" },
  { id: "q-16", name: "Background 03 B", image: "/decor03.jpg" },
  { id: "r-17", name: "Background 04 B", image: "/decor04.jpg" },
  { id: "s-18", name: "Elegant Decor B", image: "/elegent_decor.png" },
  { id: "t-19", name: "Wedding Design B", image: "/wedding.png" },
  { id: "u-20", name: "Bridal B", image: "/bridal.jpg" },
  { id: "v-21", name: "Venue B", image: "/venueCollection.jpg" },
  { id: "w-22", name: "Cake B", image: "/cakeCollection.jpg" },
  { id: "x-23", name: "Catering B", image: "/cateringCollection.jpg" },
  { id: "y-24", name: "Photography B", image: "/photographerCollection.jpg" },
  { id: "z-25", name: "Florist B", image: "/flowerColection.jpg" },
  { id: "aa-26", name: "Bridal Setup B", image: "/bridalCollection.jpg" },
  { id: "ab-27", name: "Background 01 C", image: "/decor01.jpg" },
  { id: "ac-28", name: "Background 02 C", image: "/decor02.jpg" },
  { id: "ad-29", name: "Elegant Decor C", image: "/elegent_decor.png" },
  { id: "ae-30", name: "Wedding Design C", image: "/wedding.png" },
];
